#ifndef RENDERSYSTEM_H
#define RENDERSYSTEM_H

//-----------------------------------------------------------------------------
// Render System
//
// Better use this with RTTI
//-----------------------------------------------------------------------------

//#include "color.h"
#include "com_model.h"
#include "r_studioint.h"
#include "studio_util.h"

extern vec3_t ev_punchangle;

// TODO: make a good factory and use scripts
typedef enum rendersystemtype_e
{
	RSTYPE_SYSTEM = 0,
	RSTYPE_ROTATING,
//...
};

//-----------------------------------------------------------------------------
// Basic Render System, root class for all systems.
// This is a simple square non-rotating surface (sprite).
//-----------------------------------------------------------------------------
class CRenderSystem
{
	friend class CRenderManager;// allow manager to access protected data

public:
	CRenderSystem(void);
	CRenderSystem(const Vector &origin, const Vector &origindelta, const Vector &angles, int sprindex, int r_mode, byte r, byte g, byte b, float a, float adelta, float scale, float scaledelta, float frame, float framerate, float timetolive);
	virtual ~CRenderSystem(void);// ALL RS DESTRUCTORS MUST BE DECLARED AS VIRTUAL

	virtual void ResetParameters(void);// XDM3035: UNDONE: does not work as desired!
	virtual bool Update(const float &time, const double &elapsedTime);
//	virtual void RenderOpaque(void);
//	virtual void PreFrame(void);
	virtual void Render(void);
	virtual void CreateEntities(void);
	virtual void InitializeSystem(void);
	virtual void KillSystem(void);
	virtual cl_entity_t *FollowEntity(void);
	virtual void FollowUpdatePosition(void);// XDM3035c: must be fast
	virtual void UpdateFrame(const float &time, const double &elapsedTime);
	virtual void ApplyForce(const Vector &origin, const Vector &force, float radius, bool point);
	virtual bool IsRemoving(void) { return removenow; };// Render System is about to be removed! Don't do anything with it!
	virtual unsigned int GetType(void) { return RSTYPE_SYSTEM; }
	void DrawContentsAdd(short contents);
	void DrawContentsRemove(short contents);
	bool DrawContentsHas(short contents);
	void DrawContentsClear(void);
	bool DrawContentsCheck(const Vector &origin);

	bool InitTexture(const int &texture_index);
	bool PointIsVisible(const Vector &point);

	unsigned int GetIndex(void) { return index; };
//	int GetSpriteIndex(void) { return texindex; };

	Vector m_vecOrigin;
	Vector m_vecVelocity;
	Vector m_vecAngles;
// TODO:	Vector m_vecScale;
	Vector m_vecOffset;

	float m_fStartTime;// XDM3035b: remember when the system was started
	float m_fDieTime;// exact time at which the system will be deleted
	float m_fScale;
	float m_fScaleDelta;
	float m_fBrightness;
	float m_fBrightnessDelta;
	float m_fFrame;// must be float, so it can accumulate half-frames generated by elapsedTime
	float m_fFrameRate;
	float m_iFrame;

	color24/*::Color*/ m_color;// TODO: use float? Use ::Color which includes alpha itself!
	float m_fColorDelta[3];
//	color24 m_colordelta;

	float m_fSizeX;// system dimensions, these are actually texture half-sizes
	float m_fSizeY;

	int m_iRenderMode;// standard engine render mode
//	int m_iRenderEffects;// undone
	short m_iDrawContents;// draw only in specified type of environment contents (CONTENTS_WATER, etc.)

	int m_iFlags;// RS flags, assigned by manager AFTER constructor, so don't rely on this too early!
	int m_iFollowFlags;
	int m_iFollowEntity;// is it a bad idea to store entity pointer?
	short m_iFollowAttachment;
	//int m_iFollowBoneIndex;//follow specified model bone?
	cl_entity_t *m_LastFollowedEntity;

	bool dying;// mark for removal on current/next frame. Don't mess with this!

	model_s *m_pTexture;

//	unsigned int cutom_id;// TODO: some server(user)-defined ID to search by
//	bool (*m_UpdateCallback)(CRenderSystem *pSystem, const float &time, const double &elapsedTime);// set to NULL somewhere before updating the system
protected:
	unsigned int index;
	int texindex;
	bool removenow;// use in constructors to prevent system initialization

	CRenderSystem *m_pNext;
};

#endif // RENDERSYSTEM_H
