#ifndef DECALS_H
#define DECALS_H

// Dynamic Decals
enum decal_e
{
	DECAL_ACID_SPLAT1 = 0,
	DECAL_ACID_SPLAT2,
	DECAL_ACID_SPLAT3,
	DECAL_GUNSHOT1,
	DECAL_GUNSHOT2,
	DECAL_GUNSHOT3,
	DECAL_GUNSHOT4,
	DECAL_GUNSHOT5,
	DECAL_LARGESHOT1,
	DECAL_LARGESHOT2,
	DECAL_LARGESHOT3,
	DECAL_LARGESHOT4,
	DECAL_LARGESHOT5,
	DECAL_LAMBDA1,
	DECAL_LAMBDA2,
	DECAL_LAMBDA3,
	DECAL_LAMBDA4,
	DECAL_LAMBDA5,
	DECAL_LAMBDA6,
	DECAL_SCORCH1,
	DECAL_SCORCH2,
	DECAL_SCORCH3,
	DECAL_BLOOD1, 
	DECAL_BLOOD2, 
	DECAL_BLOOD3, 
	DECAL_BLOOD4, 
	DECAL_BLOOD5, 
	DECAL_BLOOD6, 
	DECAL_YBLOOD1, 
	DECAL_YBLOOD2, 
	DECAL_YBLOOD3, 
	DECAL_YBLOOD4, 
	DECAL_YBLOOD5, 
	DECAL_YBLOOD6, 
	DECAL_GLASSBREAK1,
	DECAL_GLASSBREAK2,
	DECAL_GLASSBREAK3,
	DECAL_BIGSHOT1,
	DECAL_BIGSHOT2,
	DECAL_BIGSHOT3,
	DECAL_BIGSHOT4,
	DECAL_BIGSHOT5,
	DECAL_GAUSSSHOT1,
	DECAL_SPIT1,
	DECAL_SPIT2,
	DECAL_SPLAT7,
	DECAL_SPLAT8,
	DECAL_BPROOF1,		// Bulletproof glass decal
	DECAL_GARGSTOMP1,	// Gargantua stomp crack
	DECAL_SMALLSCORCH1,	// Small scorch mark
	DECAL_SMALLSCORCH2,	// Small scorch mark
	DECAL_SMALLSCORCH3,	// Small scorch mark
	DECAL_MOMMABIRTH,	// Big momma birth splatter
	DECAL_MOMMASPLAT,
	DECAL_NUCBLOW1,
	DECAL_NUCBLOW2,
	DECAL_NUCBLOW3,
	DECAL_WOODBREAK1,
	DECAL_WOODBREAK2,
	DECAL_WOODBREAK3,
	DECAL_BBLOOD1, 
	DECAL_BBLOOD2, 
	DECAL_BBLOOD3, 
	DECAL_GBLOOD1, 
	DECAL_GBLOOD2, 
	DECAL_GBLOOD3, 
	DECAL_MDSCORCH1,
	DECAL_MDSCORCH2,
	DECAL_MDSCORCH3,
	DECAL_BIOHAZ,
	DECAL_BLOODSMEARR1,
	DECAL_BLOODSMEARR2,
	DECAL_BLOODSMEARR3,
	DECAL_BLOODSMEARY1,
	DECAL_BLOODSMEARY2,
	DECAL_BLOODSMEARY3,
	DECAL_BLOW,
	DECAL_MINISCORCH1,
	DECAL_MINISCORCH2,
	DECAL_MINISCORCH3,
	DECAL_BLASTSCORCH1,
	DECAL_BLASTSCORCH2,
	DECAL_BLASTSCORCH3,
	DECAL_EXPSCORCH1,
	DECAL_EXPSCORCH2,
	DECAL_EXPSCORCH3,
	DECAL_OFSCORCH1,
	DECAL_OFSCORCH2,
	DECAL_OFSCORCH3,
	DECAL_GLUONSCORCH1,
	DECAL_GLUONSCORCH2,
	DECAL_GLUONSCORCH3,
	DECAL_BEAMSHOT1,
	DECAL_BEAMSHOT2,
	DECAL_BEAMSHOT3,
	DECAL_FROSTSCORCH1,
	DECAL_FROSTSCORCH2,
	DECAL_FROSTSCORCH3,
	DECAL_ACID_BIGSPLAT1,
	DECAL_ACID_BIGSPLAT2,
	DECAL_ACID_BIGSPLAT3,
	DECAL_ENUM_SIZE// last element represents enum size
};

typedef struct
{
	char	*name;
	int		index;
} DLL_DECALLIST;

extern DLL_DECALLIST g_Decals[DECAL_ENUM_SIZE];

#endif // DECALS_H
