//====================================================================
// All shared weapon-related definitions are now here.
//====================================================================
#ifndef WEAPONDEF_H
#define WEAPONDEF_H
#ifdef _WIN32
#ifndef __MINGW32__
#pragma once
#endif /* not __MINGW32__ */
#endif

// XDM: moved to header
#define	SF_NODAMAGE		0x0001 // when set, ENV_EXPLOSION will not actually inflict damage
#define	SF_REPEATABLE	0x0002 // can this entity be refired?
#define SF_NOFIREBALL	0x0004 // don't draw the fireball
#define SF_NOSMOKE		0x0008 // don't draw the smoke
#define SF_NODECAL		0x0010 // don't make a scorch mark
#define SF_NOSPARKS		0x0020 // don't create sparks
//#define SF_NOPARTICLES	0x0040 // don't create particles
#define SF_NOSOUND		0x0080 // don't create sound
#define SF_NUCLEAR		0x0100 // nuclear
// Grenades flagged with this will be triggered when the owner calls detonateSatchelCharges
#define SF_DETONATE		0x0800 // XDM: internal constant, no matther what value it has



// constant items XDM: moved to "items.h"

// Weapon IDs. Maximum 32 weapons, see MAX_WEAPONS in "protocol.h"
enum WEAPONS
{
	WEAPON_NONE = 0,
	WEAPON_TYRIANGUN,
	WEAPON_SUIT
};

#define WEAPON_ALLWEAPONS		(~(1<<WEAPON_SUIT))


// bullet types
typedef	enum
{
	BULLET_NONE = 0,
	BULLET_MACHINEGUN,
	BULLET_MINIGUN,
	BULLET_VULCAN,
	BULLET_RAILGUN,
	BULLET_SUPERRAILGUN,
	BULLET_LASER,
	BULLET_GAUSS,
	BULLET_SHOCK,
	BULLET_LIGHTNING,
	BULLET_TWINLASER,
	BULLET_TAUCANNON,
	BULLET_BEAMSPLITTER,
	BULLET_HEAVY_TURRET,
	BULLET_MEZONCANNON,
	BULLET_BUCKSHOT,
	BULLET_PHOTONGUN,
	BULLET_BFG,
	BULLET_CLUSTERGUN,
	BULLET_FLAK_CANNON,
	BULLET_NEYTRONGUN,
	BULLET_PLASMABALL,// draws normal-oriented effects
	BULLET_TRIDENT,// draws normal-oriented effects
	FX_PLAYER_GIB_ELECTROCUTED,// player elecrogib fx, moved here, cause we need to sent "angles" to client
} Bullet;

// lightning types
typedef	enum
{
	TYPE_LGTNG_BEAM  = 0,
	TYPE_LIGHTNING_BALL_BEAM,
	TYPE_GHOSTMISSILE_BEAM,
	TYPE_PARTICLE_BEAM,
} Lgtng;

#define ITEM_FLAG_SELECTONEMPTY		1
#define ITEM_FLAG_NOAUTORELOAD		2
#define ITEM_FLAG_NOAUTOSWITCHEMPTY	4
#define ITEM_FLAG_LIMITINWORLD		8
#define ITEM_FLAG_EXHAUSTIBLE		16// A player can totally exhaust their ammo supply and lose this weapon
#define ITEM_FLAG_CANNOTDROP		32// XDM
#define ITEM_FLAG_SUPERWEAPON		64// XDM3035 this is a powerful weapon

typedef struct
{
#ifdef SERVER_WEAPON_SLOTS
	int		iSlot;
	int		iPosition;
#endif
	const char	*pszAmmo1;	// ammo 1 type
	int		iMaxAmmo1;		// max ammo 1
	const char	*pszAmmo2;	// ammo 2 type
	int		iMaxAmmo2;		// max ammo 2
	const char	*pszName;
	int		iMaxClip;
	int		iId;
	int		iFlags;
	int		iWeight;// this value used to determine this weapon's importance in autoselection.
} ItemInfo;

#define MAX_AMMO_NAME_LEN 16

typedef struct
{
	char	name[MAX_AMMO_NAME_LEN];
	int		iMaxCarry;
//	int iId;
} AmmoInfo;

#define LOUD_GUN_VOLUME			1000
#define NORMAL_GUN_VOLUME		600
#define QUIET_GUN_VOLUME		200

#define	BRIGHT_GUN_FLASH		512
#define NORMAL_GUN_FLASH		256
#define	DIM_GUN_FLASH			128

#define BIG_EXPLOSION_VOLUME	2048
#define NORMAL_EXPLOSION_VOLUME	1024
#define SMALL_EXPLOSION_VOLUME	512

#define	WEAPON_ACTIVITY_VOLUME	64

#define VECTOR_CONE_0DEGREES	Vector(0.00000, 0.00000, 0.00000)
#define VECTOR_CONE_1DEGREES	Vector(0.00436, 0.00436, 0.00436)
#define VECTOR_CONE_2DEGREES	Vector(0.00872, 0.00872, 0.00872)
#define VECTOR_CONE_3DEGREES	Vector(0.01309, 0.01309, 0.01309)
#define VECTOR_CONE_4DEGREES	Vector(0.01745, 0.01745, 0.01745)
#define VECTOR_CONE_5DEGREES	Vector(0.02181, 0.02181, 0.02181)
#define VECTOR_CONE_6DEGREES	Vector(0.02617, 0.02617, 0.02617)
#define VECTOR_CONE_7DEGREES	Vector(0.03052, 0.03052, 0.03052)
#define VECTOR_CONE_8DEGREES	Vector(0.03488, 0.03488, 0.03488)
#define VECTOR_CONE_9DEGREES	Vector(0.03923, 0.03923, 0.03923)
#define VECTOR_CONE_10DEGREES	Vector(0.04358, 0.04358, 0.04358)
#define VECTOR_CONE_12DEGREES	Vector(0.04978, 0.04978, 0.04978)
#define VECTOR_CONE_15DEGREES	Vector(0.06526, 0.06526, 0.06526)
#define VECTOR_CONE_20DEGREES	Vector(0.08682, 0.08682, 0.08682)

#define VECTOR_CONE_25DEGREES	Vector(0.10863, 0.10863, 0.10863)
#define VECTOR_CONE_30DEGREES	Vector(0.13044, 0.13044, 0.13044)
#define VECTOR_CONE_35DEGREES	Vector(0.15225, 0.15225, 0.15225)

// XDM
#define VECTOR_CONE_40DEGREES	Vector(0.34730, 0.34730, 0.34730)
#define VECTOR_CONE_45DEGREES	Vector(0.41792, 0.41792, 0.41792)
#define VECTOR_CONE_LOTS		Vector(0.5f, 0.5f, 0.5f)

//super weapon ammo
#define MAX_AMMO_SUPERWEAPON	100

// how much energy the generator produses at base level 
#define GENERATOR_PROVIDE_POWER	25

//max. power level
#define	POWER_MAX_CHARGE					2000
#define	POWER_MAX_CHARGE_GUIDED_BOMB	 	2100
#define	POWER_MAX_CHARGE_PROTON_MISSILE 	2200
#define	POWER_MAX_CHARGE_DISPLACER 			2300
#define	POWER_MAX_CHARGE_SHOCK_WAVE 		2400
#define	POWER_MAX_CHARGE_NUCLEAR_MISSILE	2600
#define	POWER_MAX_CHARGE_CHRONOSCEPTRE		2800
#define	POWER_MAX_CHARGE_SUN_OF_GOD			3000


//invisibility 
#define INVISIBILITY_RENDERAMT	20

//items max carry
#define MAX_FLASHBANG_CARRY			10
#define MAX_AIRSTRIKE_CARRY			8
#define MAX_SATELLITE_STRIKE_CARRY	4
#define MAX_TRIPMINE_CARRY			12
#define MAX_SPIDERMINE_CARRY		6
#define MAX_ANTIDOTE_CARRY			10
#define MAX_FIRE_SUPRESSORS_CARRY	10
#define MAX_ENERGY_CUBE_CARRY		100

//max augmentations
#define MAX_GENERATOR_AUG	5
#define MAX_HEALTH_AUG		8
#define MAX_SHIELD_AUG		8
#define MAX_SHIELD_STRENGTH_AUG		5
#define MAX_WEAPON_POWER_AUG		10

// if this is set, don't draw icon
#define SHIELD_IS_DEAD		8192
#define GENERATOR_IS_DEAD	254
#define WEAPON_IS_DEAD		254

// temporary items time
#define TIME_QUAD_DAMAGE	45
#define TIME_HASTE		45
#define TIME_INVULNERABILITY	45
#define TIME_RAPID_FIRE		45
#define TIME_SHIELD_REGEN	60
#define TIME_INVISIBILITY	45
#define TIME_BANANA_WEAPON	75
#define TIME_ACCURACY		80
#define TIME_ANTIDOTE		60
#define TIME_FIRE_SUPRESSOR		40
#define TIME_LIGHTNING_FIELD	50
#define TIME_RADSHIELD		30
#define TIME_PLASMA_SHIELD		50

//weapon modifyers coefficients
#define RAPIDFIRE_MODYFIER 0.5
#define ACCURACY_MODYFIER 0.5
#define ZOOM_ACCURACY_MODYFIER 0.25
#define AMMOUSE_MODYFIER 0.5

typedef enum
{
	AIRSTRIKE_MORTAR = 0,
	AIRSTRIKE_SATELLITE,
	AIRSTRIKE_PARACHUTE
} airstrike_type;

// Super weapons ammo consumption
typedef enum
{
	AMMO_USE_BOT_WEAPON			= 10,
	AMMO_USE_GUIDED_BOMB	 	= 10,
	AMMO_USE_PROTON_MISSILE 	= 20,
	AMMO_USE_DISPLACER 			= 40,
	AMMO_USE_SHOCK_WAVE 		= 60,
	AMMO_USE_NUCLEAR_MISSILE	= 70,
	AMMO_USE_CHRONOSCEPTRE		= 80,
	AMMO_USE_SUN_OF_GOD			= 100
} sw_ammo_use;

typedef enum
{
	TYRIANGUN_NONE = 0,
	TYRIANGUN_MACHINEGUN,
	TYRIANGUN_MINIGUN,
	TYRIANGUN_VULCAN_MINIGUN,
	TYRIANGUN_HEAVY_TURRET,
	TYRIANGUN_GAUSS,
	TYRIANGUN_LASER,
	TYRIANGUN_RAILGUN,
	TYRIANGUN_SUPER_RAILGUN,
	TYRIANGUN_SHOCK_CANNON,
	TYRIANGUN_LIGHTNING,
	TYRIANGUN_TWIN_LASER,
	TYRIANGUN_TAU_CANNON,
	TYRIANGUN_MEZON_CANNON,
	TYRIANGUN_REPEATER,
	TYRIANGUN_PHOTONGUN,
	TYRIANGUN_BFG,
	TYRIANGUN_M203,
	TYRIANGUN_NEEDLE_LASER,
	TYRIANGUN_SHOCK_LASER,
	TYRIANGUN_HELL_HOUNDER,
	TYRIANGUN_30MMGRENADE,
	TYRIANGUN_MINI_MISSILE,
	TYRIANGUN_BIOHAZARD_MISSILE,
	TYRIANGUN_GLUON,
	TYRIANGUN_TRIDENT,
	TYRIANGUN_HELLFIRE,
	TYRIANGUN_PLASMA,
	TYRIANGUN_PLASMA_STORM,
	TYRIANGUN_PULSE_CANNON,
	TYRIANGUN_MULTI_CANNON,
	TYRIANGUN_SCORCHER,
	TYRIANGUN_FROSTER,
	TYRIANGUN_SONIC_WAVE,
	TYRIANGUN_CHARGE_CANNON,
	TYRIANGUN_DEMOLITION_MISSILE,
	TYRIANGUN_HVR_MISSILE,
	TYRIANGUN_MICRO_MISSILE,
	TYRIANGUN_RIPPER,
	TYRIANGUN_DISRUPTOR,
	TYRIANGUN_CLUSTER_GUN,
	TYRIANGUN_NEYTRON_GUN,
	TYRIANGUN_FLAK_CANNON,
	TYRIANGUN_STARBURST,
	TYRIANGUN_BIORIFLE,
	TYRIANGUN_BEAMSPLITTER,
	TYRIANGUN_GHOST_MISSILE,
	TYRIANGUN_SWEAPON_GUIDED_BOMB, //super weapons
	TYRIANGUN_SWEAPON_PROTON_MISSILE,
	TYRIANGUN_SWEAPON_DISPLACER,
	TYRIANGUN_SWEAPON_SHOCK_WAVE,
	TYRIANGUN_SWEAPON_NUCLEAR_LAUNCHER,
	TYRIANGUN_SWEAPON_CHRONOSCEPTRE,
	TYRIANGUN_SWEAPON_SUN_OF_GOD,
	TYRIANGUN_BANANA, //funny weapons
	TYRIANGUN_TOILET,
	TYRIANGUN_PLAYER_BLAST, //MUST be the last one
} tyriangun;

typedef enum
{
	STARTWPN_ALL = 0,
	STARTWPN_INSTAHIT,
	STARTWPN_PROJECTILE,
	STARTWPN_SMALL_DMG_RADIUS,
	STARTWPN_ROCKETS_HP_ENERGY,
} start_weapon;

//weapon fire rate
#define	FIRERATE_MACHINEGUN		0.09
#define	FIRERATE_MINIGUN		0.07	
#define	FIRERATE_VULCAN_MINIGUN	0.08
#define	FIRERATE_30MMTURRET		0.11
#define	FIRERATE_GAUSS			0.3
#define	FIRERATE_LASER			0.25
#define	FIRERATE_RAILGUN		0.6
#define	FIRERATE_SUPER_RAILGUN	0.75
#define	FIRERATE_SHOCK_CANNON	0.1
#define	FIRERATE_LIGHTNING		1.0
#define	FIRERATE_TWIN_LASER		0.22
#define	FIRERATE_TAU_CANNON		0.9
#define	FIRERATE_BEAMSPLITTER	0.5
#define	FIRERATE_MEZON_CANNON	0.45
#define	FIRERATE_REPEATER		0.25
#define	FIRERATE_FLAK_CANNON	0.9
#define	FIRERATE_PHOTONGUN		0.2
#define	FIRERATE_BFG			1.0
#define	FIRERATE_M203			0.6
#define	FIRERATE_NEEDLE_LASER	0.1
#define	FIRERATE_BIORIFLE		0.28
#define	FIRERATE_SHOCK_LASER	0.12
#define	FIRERATE_HELL_HOUNDER	1.0
#define	FIRERATE_30MMGRENADE	0.7
#define	FIRERATE_MINI_MISSILE	0.5
#define	FIRERATE_BIOHAZARD_MISSILE	0.85
#define	FIRERATE_TOILET			1.05
#define	FIRERATE_BANANA			0.15
#define	FIRERATE_GLUON			0.75
#define	FIRERATE_TRIDENT		0.62
#define	FIRERATE_HELL_FIRE		1.1
#define	FIRERATE_PLASMA			0.25
#define	FIRERATE_PLASMA_STORM	0.7
#define	FIRERATE_PULSE_CANNON	0.09
#define	FIRERATE_MULTI_CANNON	0.2
#define	FIRERATE_SCORCHER		0.75
#define	FIRERATE_FROSTER		0.22
#define	FIRERATE_SONIC_WAVE		0.5
#define	FIRERATE_CHARGE_CANNON	0.35
#define	FIRERATE_DEMOLITION_MISSILE	1.3
#define	FIRERATE_GHOST_MISSILE	0.9
#define	FIRERATE_HVR_MISSILE	0.95
#define	FIRERATE_MICRO_MISSILE	0.5
#define	FIRERATE_RIPPER			0.25
#define	FIRERATE_DISRUPTOR		0.8
#define	FIRERATE_GUIDEDBOMB		1.3
#define	FIRERATE_CLUSTER_GUN	0.65
#define	FIRERATE_NEYTRON_GUN	0.08
#define	FIRERATE_STARBURST		1.0

//fire spread for projectiles
#define	FIRESPREAD_30MMGRENADE		30
#define	FIRESPREAD_M203GRENADE		34
#define	FIRESPREAD_HELL_HOUNDER		13
#define	FIRESPREAD_BANANA			35
#define	FIRESPREAD_TOILET			28
#define FIRESPREAD_CHARGE_CANNON	24
#define FIRESPREAD_PLASMA			35
#define FIRESPREAD_PLASMASTORM		38
#define FIRESPREAD_GLUONGUN			30
#define FIRESPREAD_TRIDENT			60
#define FIRESPREAD_MULTI_CANNON		18
#define FIRESPREAD_PULSE_CANNON		45
#define FIRESPREAD_SHOCK_LASER		22
#define FIRESPREAD_NEEDLE_LASER		20
#define FIRESPREAD_BIORIFLE			30
#define FIRESPREAD_CLUSTER_GUN		25
#define FIRESPREAD_SONIC_WAVE		36
#define FIRESPREAD_FROSTER			24
#define FIRESPREAD_SCORCHER			35
#define FIRESPREAD_RIPPER			30
#define	FIRESPREAD_MINI_MISSILE		15
#define	FIRESPREAD_MICRO_MISSILE	20
#define	FIRESPREAD_FLASHBANG		20
#define	FIRESPREAD_STARBURST		240
#define	FIRESPREAD_HELLFIRE			32
#define FIRESPREAD_GHOST_MISSILE	19
#define FIRESPREAD_GUIDED_BOMB		30
#define FIRESPREAD_BIOHAZARD_MISSILE	15
#define FIRESPREAD_PLASMA_SHIELD_CHARGE	26
#define	FIRESPREAD_DEMOLITION_MISSILE	20


//projectile velocity
#define SPEED_PLASMA_SHIELD_CHARGE	2400
#define SPEED_30MM_GRENADE			1800
#define SPEED_M203_GRENADE			1600
#define SPEED_DISRUPTOR_BALL		2800
#define SPEED_BIOHAZARD_MISSILE		1850
#define SPEED_GLUON_BALL			2500	
#define SPEED_TRIDENT				3300	
#define SPEED_SUN_OF_GOD			320
#define SPEED_ACID_BLOB				1500	
#define SPEED_AIRSTRIKE_TARGET		300	
#define SPEED_ANTIMATHERIAL_MISSILE	900	
#define SPEED_BANANA				1400	
#define SPEED_CHARGECANNON			3500	
#define SPEED_DEMOLITION_MISSILE	1500	
#define SPEED_FLASHBANG				800	
#define SPEED_FROST_BALL			3000	
#define SPEED_GHOST_MISSILE			850	
#define SPEED_GUIDED_BOMB			1250
#define SPEED_GUIDED_SHARD			800	
#define SPEED_HELLFIRE				1000	
#define SPEED_HELLHOUNDER			2000
#define SPEED_HVR_MISSILE			1000	
#define SPEED_LIGHTNING_BALL		750	
#define SPEED_MICRO_MISSILE			2400
#define SPEED_MINI_MISSILE			2100
#define SPEED_MULTI_CANNON			5000
#define SPEED_NEEDLE_LASER			4500	
#define SPEED_NUCLEAR_MISSILE		800		
#define SPEED_PLASMA_BALL			4700
#define SPEED_PLASMA_STORM			4000
#define SPEED_PROTON_MISSILE		1250
#define SPEED_PULSE_CANNON_BALL		3750	
#define SPEED_RIPPER				2500
#define SPEED_SCORCHER				2450
#define SPEED_SHOCK_LASER			4200
#define SPEED_SONIC_WAVE			4800
#define SPEED_STARBURST				30000	
#define SPEED_TELEPORTER			1200	
#define SPEED_TOILET				750

#endif // WEAPONDEF_H
